### ISSUE TITLE
Docker コンテナの起動に失敗する

### ISSUE THREAD

**Issue by azuki-penguin** [coderdojo-japan/dojocon2023.coderdojo.jp#10]
### 概要

`docker compose up -d` を実行すると、コンテナの起動に失敗しました。
イメージ が pull されたあと、 コンテナを起動する際に以下のメッセージが表示されていました。

```
jekyll The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
```

Docker Hub に push されている docker image の CPU アーキテクチャが ARM64 になっていることが原因のようです。
そのため、 CPU アーキテクチャが x86_64 などの環境では起動できないかもしれません。

```bash
$ docker image inspect coderdojojapan/dojocon-japan-2023:latest | grep Architecture
        "Architecture": "arm64",
```

### 実行環境

以下の環境で事象が発生することを確認しました。

**Linux**
- CPU: AMD® Ryzen 9 5950x 16-core processor × 32
- OS: Ubuntu 22.04.2 LTS
- Docker version 23.0.1, build a5ee5b1

**MacOS**
- CPU: 2.3 GHz Dual-Core Intel Core i5
- OS: macOS 13.1
- Docker version 20.10.23, build 7155243

**Comment by kwaka1208** [comment]
なるほど、みんなでM1かM2のMacを買うしかないな....。

冗談はさておき、これって両方対応できますか？ @yasulab

**Comment by yasulab** [comment]
ちょっと試してみますね〜 👀💨

**Comment by azuki-penguin** [comment]
再度 macOS の方を確認してみたら、警告は出ているものの、コンテナは立ち上がっていました...

**Comment by yasulab** [comment]
お、無事に表示されたようでよかったです！(๑•̀ㅂ•́)و✨
一旦問題は解決したと思うので Close しておきますね! ✅
